const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./endpoints.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "Crypto Coin Easy API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "GET",
            "description": "Endpoint to get the informations about some coin."
        }
    ],
    definitions: {
        Response: {
            "succeed": true,
            "status": 200,
            "message": "OK",
            "update": 1638295465671,
            "content": {
                "name": "CryptoMines Eternal",
                "symbol": "ETERNAL",
                "price": "291.980736788007684237953066731"
            }
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
})